alias gac='git add $(git rev-parse --show-cdup).;git commit'
alias gs='git status'
alias gb='git branch'
alias gco='git checkout'
alias gcb='git checkout master && git pull && git checkout -b'
alias gl='git log --oneline --decorate'
